### ISSUE TITLE
Incorrect validation with valid

### ISSUE THREAD

**Issue by doxmazz** [dashbitco/nimble_totp#26] opened 2023-08-17 16:12 UTC
### Context

I'm generating OTP for sms validation (not for 2FA apps) and storing the secret in our DB as binary (without encoding), and I've set the OTP valid period to 300 (5 mins).
But sometimes when I'm trying to call `NimbleTOTP.valid?(secret, otp, time: time, period: 300)` it throws `false` even when I try to validate within a minute.

This is how I generate code 
```elixir
    secret = NimbleTOTP.secret(20)
    time = System.os_time(:second)
    otp_code = NimbleTOTP.verification_code(secret, time: time, period: 300)
```

It does not reproduce every time, happens randomly like 2 out of 10.

**Comment by wojtekmach** [comment] 2023-08-17 18:08
> `NimbleTOTP.valid?(secret, otp, time: time, period: 300)`

what is the `time` value that you are passing?

Could you try writing a script that reproduces the issue?

**Comment by doxmazz** [comment] 2023-08-17 18:29
`time = System.os_time(:second)`

**Comment by PJUllrich** [comment] 2024-06-20 17:29
@wojtekmach @whatyouhide sorry folks, but something's off here or I'm understanding the options wrong.

I created a test script because I also ran into issues where the code stopped working unexpectedly. The full script is below, but here's what I expected, how I tested it, and what the results where:

1. **If I create a code now and verify it every second for 30 seconds, it will be invalid after exactly 30 seconds.**

```elixir
secret = NimbleTOTP.secret()
code = NimbleTOTP.verification_code(secret)
for _sec <- 1..60 do
  NimbleTOTP.valid?(secret, code) |> IO.inspect(label: DateTime.utc_now())
  :timer.sleep(1000)
end
```

-> The code stopped working at every 0s and 30s mark of the minute. So, if I created a code at 12:00:54, it would stop working at 12:01:00. Same for 12:00:24, which stopped working at 12:00:30. 

2. **If I validate a code with `period: 60`, it will be valid for 60 seconds instead of 30s.**

```elixir
secret = NimbleTOTP.secret()
code = NimbleTOTP.verification_code(secret)
for _sec <- 1..90 do
  NimbleTOTP.valid?(secret, code, period: 60) |> IO.inspect(label: DateTime.utc_now())
  :timer.sleep(1000)
end
```

-> The very first call is `false` already.

3. **If I create a code with `period: 60` and validate it with `period: 60`, it will be valid for 60s.**
```elixir
secret = NimbleTOTP.secret()
code = NimbleTOTP.verification_code(secret, period: 60)
for _sec <- 1..90 do
  NimbleTOTP.valid?(secret, code, period: 60) |> IO.inspect(label: DateTime.utc_now())
  :timer.sleep(1000)
end
```

-> The code stopped working at "random" times, but mostly on the minute or at the 30s mark. One time it stopped working on the minute after ~15s of running the test and one time it stopped 47s later (started at 12:00:37, stopped at 12:01:24), one time started at 12:00:53, stopped being valid at 12:01:00. It seems like the `period`-option has no effect?

Here's also a more verbose test Livebook:
--- 
# NimbleTOTP LiveBook 

```elixir
Mix.install([
  {:nimble_totp, "~> 1.0"}
])
```

## Test

```elixir
defmodule Tester do
  require Logger

  def run(true, secret, code, period) do
    Logger.debug("True. Sleeping...")
    :timer.sleep(1_000)

    secret
    |> NimbleTOTP.valid?(code, period: period)
    |> run(secret, code, period)
  end

  def run(false, _secret, _code, _period) do
    Logger.debug("False!")
    System.os_time(:second)
  end
end
```

```elixir
secret = NimbleTOTP.secret()
# 45s instead of 30s
period = 45
code = NimbleTOTP.verification_code(secret, period: period)

NimbleTOTP.valid?(secret, code, period: period) |> IO.inspect(label: "Start:")

Tester.run(true, secret, code, period)
```

---

**Comment by josevalim** [comment] 2024-06-20 17:57
It has been a while but don’t you have to pass the same period option both when generating the code and when validating it? We can probably improvise the docs around this.

**Comment by josevalim** [comment] 2024-06-20 17:58
Also, keep in mind that TOTP is periodic. You can generate a TOTP now but it is in its last minute out of 5. So I don’t think it works for what you want. You could use Phoenix.Token instead.

**Closed** 2024-06-21 06:51 UTC
